Fix actions

diff --git a/.github/actions/style/action.yml b/.github/actions/style/action.yml
--- a/.github/actions/style/action.yml
+++ b/.github/actions/style/action.yml
@@ -7,24 +7,32 @@ runs:
     - name: "Run clang-format"
       shell: bash
       run: |
-          # We only make check, not changes
-          # Use the find command with the variable
-          PROJECT_PATH=$(pwd)
-          # ToDo: Add documentation about 'tr' command and describe better this command
-          SOURCE_FILES=$(find $PROJECT_PATH -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")
+        # We only make check, not changes
+        # Use the find command with the variable
+        PROJECT_PATH=$(pwd)
 
-          ERROR_FILE_FLAG=$PROJECT_PATH/ci/clang-format_errors.txt
+        echo $PROJECT_PATH
 
-          # ToDo: Add documentation and describe better this command
-          CLANG_COMMAND=$(clang-format --dry-run -i $SOURCE_FILES) 2> $ERROR_FILE_FLAG
+        # ToDo: Add documentation about 'tr' command and describe better this command
+        SOURCE_FILES=$(find $PROJECT_PATH/src -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")
+        SOURCE_FILES+=$(find $PROJECT_PATH/include -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")
+        SOURCE_FILES+=$(find $PROJECT_PATH/lib -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")
 
-          if [ -s $ERROR_FILE_FLAG ]; then
-              echo "Error: There are some files that are not formatted correctly"
-              exit 1
-          else
-              echo "All files are formatted correctly. Niiiceee"
-              exit 0
-          fi
+        ERROR_FILE_FLAG=$PROJECT_PATH/ci/clang-format_errors.txt
+
+        # ToDo: Add documentation and describe better this command
+        CLANG_COMMAND=$(clang-format -i $SOURCE_FILES) 2> ${ERROR_FILE_FLAG}
+
+        echo "Running: clang-format -i $SOURCE_FILES"
+
+        if [ -s $ERROR_FILE_FLAG ]; then
+            echo "Error: There are some files that are not formatted correctly"
+            exit 1
+        else
+            echo "All files are formatted correctly. Niiiceee"
+            exit 0
+        fi
+
     # Upload errors as an artifact, when failed
     - uses: actions/upload-artifact@v3
       if: failure()
