Fix coverage

diff --git a/.github/actions/coverage_and_test/action.yml b/.github/actions/coverage_and_test/action.yml
--- a/.github/actions/coverage_and_test/action.yml
+++ b/.github/actions/coverage_and_test/action.yml
@@ -7,28 +7,33 @@ runs:
     - name: "Run coverage"
       shell: bash
       run: |
-          PROJECT_PATH=$(pwd)
+        PROJECT_PATH=$(pwd)
 
-          # ToDo: Add documentation and describe better this command
-          ctest --test-dir build/tests --output-on-failure
+        # ToDo: Add documentation and describe better this command
+        ctest --test-dir build/tests --output-on-failure
 
-          # ToDo: Add documentation and describe better this command
-          gcovr -r $PROJECT_PATH $PROJECT_PATH/build > $PROJECT_PATH/coverage.txt
+        # ToDo: Add documentation and describe better this command
 
-          cat $PROJECT_PATH/coverage.txt
 
-          # Find the value of correct coverage
-          # ToDo: Add documentation and describe better this command
-          linesCoverage=$(cat $PROJECT_PATH/coverage.txt | grep -oP 'TOTAL.*\K\d+\.\d+')
+        gcovr -r $PROJECT_PATH . > $PROJECT_PATH/coverage.txt
 
-          # Check if the coverage is greater than 20%
-          if (( $(echo "$linesCoverage > 20" | bc -l) )); then
-              echo "Coverage is greater than 20%. Niiiceee"
-              exit 0
-          else
-              echo "Error: Coverage is less than 20%"
-              exit 1
-          fi
+        echo "Runnig: gcovr -r $PROJECT_PATH ."
+
+        cat $PROJECT_PATH/coverage.txt
+
+        # Find the value of correct coverage
+        # ToDo: Add documentation and describe better this command
+        COVERAGE_RESULT=$(grep "TOTAL" $PROJECT_PATH/coverage.txt | awk '{print $NF}' | cut -d '%' -f 1)
+
+        # Coverage lines GT 20
+        if [ "$(echo "$COVERAGE_RESULT > 20" | bc)" -eq 1 ]; then
+            echo "Coverage is greater than 20%. Nice!"
+            exit 0
+        else
+            echo "Error: Coverage is less than or equal to 20%"
+            exit 1
+        fi
+
     # Upload errors as an artifact, when failed
     - uses: actions/upload-artifact@v3
       if: failure()
